apiVersion: v1
kind: Service
metadata:
  name: inference
  labels:
    app: inference
spec:
  ports:
  - port: 5005
    targetPort: 5000
    protocol: TCP
  clusterIP: None
  selector:
    app: inference
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
  labels:
    app: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: inference
        image: so1sservice
        imagePullPolicy: Never
        ports:
          - containerPort: 5000
