apiVersion: batch/v1
kind: Job
metadata:
  name: builder
spec:
  template:
    spec:
      initContainers:
        # This container clones the desired git repo to the EmptyDir volume.
        - name: git-clone
          image: alpine/git # Any image with git will do
          args:
            - clone
            - --single-branch
            - --
            - https://github.com/So1S/So1S-PoC-dps0340 # Your repo
            - /repo # Put it in the volume
          securityContext:
            runAsUser: 1 # Any non-root user will do. Match to the workload.
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: git-repo
              mountPath: /repo
        # This container clones the desired git repo to the EmptyDir volume.
        - name: build-clone
          image: alpine/git # Any image with git will do
          args:
            - clone
            - --single-branch
            - --
            - https://github.com/So1S/So1S-PoC-bentoml # Your repo
            - /repo # Put it in the volume
          securityContext:
            runAsUser: 1 # Any non-root user will do. Match to the workload.
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: build-repo
              mountPath: /repo         
      containers:
        - name: builder
          image: builder
          command: ["/bin/sh"]
          args: ["/usr/src/git-repo/inference/run.sh"]
          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket-volume
          - mountPath: /usr/src/git-repo
            name: git-repo
          - mountPath: /usr/src/build-repo
            name: build-repo
          securityContext:
            privileged: true
      restartPolicy: Never
      volumes:
        - name: docker-socket-volume
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: git-repo
          emptyDir: {}
        - name: build-repo
          emptyDir: {}