apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: inference
build:
  artifacts:
  - image: builder
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - job.yaml
